### PR TITLE
:sparkles: Make feature_auth_required false by default

### PR DESCRIPTION
**Pull request by jmontleon**
Requested that konveyor not require auth by default.

### CODE REVIEW

**Review by jortel — DISMISSED** [review]
LGTM

**Comment by jwmatthews** [comment]
Thanks @jmontleon 

Fixes https://github.com/konveyor/enhancements/issues/115

**Comment by djzager** [comment]
VISACK, but I'll leave it for @fbladilo to approve.

**Review by fbladilo — APPROVED** [review]
LGTM

**Pull request merged**
