### PR TITLE
Replace keycloak_sso with keycloak

### PR DESCRIPTION
**Pull request by gildub**

### CODE REVIEW

**Comment by gildub** [comment]
@fbladilo, this is follow-up konveyor/tackle2-ui#64

**Comment by fbladilo** [comment]
@gildub Needs a rebase when you get a chance...

**Comment by gildub** [comment]
@fbladilo, are we still doing this one ? Or maybe after 2.0 GA ?

**Comment by fbladilo** [comment]
Closing in favor of #45

**Pull request closed without merging**
